# Generated by Django 4.0.6 on 2022-07-30 12:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='publish',
            field=models.DateField(default=datetime.datetime(2022, 7, 30, 17, 18, 54, 810540)),
        ),
    ]
